INSERT INTO symptom (sname) VALUES
('loss of appetite'),
('abdominal distenion'),
('indigestion'),
('emaciation'),
('itchiness'),
('arrythmia'),
('swelling'),
('chest pain'),
('joint pain'),
('dyspnea'),
('polyuria'),
('hematuria'),
('yellow skin'),
('yellow sclera'),
('ulcer'),
('discoloration'),
('fever'),
('nausea'),
('polydipsia'),
('cough'),
('paralysis'),
('hypoglycemia'),
('anemia'),
('lethargy'),
('constipation'),
('boil'),
('leucorrhea'),
('menorrhagia'),
('metrorrhagia'),
('hepatitis'),
('malaria'),
('rhinitis'),
('akathisia');